CollectAll/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('collection_list/', views.CollectionListView.as_view(), name='collection_list'),
	path('collection_detail/<int:pk>/', views.CollectionDetailView.as_view(), name='collection_detail'),
	path('personal_list/', views.PersonalCollectionListView.as_view(), name='personal_list'),
	path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
	path('collection/create/', views.create_collection, name='collection_create'),
	path('collection/<int:pk>/update/', views.CollectionUpdate.as_view(), name='collection_update'),
	path('collection/<int:pk>/delete/', views.collection_delete, name='collection_delete'),
	path('search_collections/', views.search_collections, name='search_collections'),
]

Group7Collect/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	              path('admin/', admin.site.urls),
	              path('', include('CollectAll.urls')),
	              path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
	              path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	              path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
	                   name='password_reset_confirm'),
	              path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
	              path('accounts/', include('django.contrib.auth.urls')),
	              path('', include('register.urls')),
	              path('', include('contact_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
]

CollectAll/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser


class Collection(models.Model):
	name = models.CharField(max_length=200, help_text='Enter a Collection Title')
	private = models.BooleanField()
	favorite = models.BooleanField()
	notes = models.TextField()
	collectionType = models.ForeignKey('CollectionType', on_delete=models.RESTRICT, null=True)
	siteUser = models.ForeignKey('SiteUser', on_delete=models.RESTRICT, null=True)
	parent = models.ForeignKey('Collection', on_delete=models.RESTRICT, null=True, blank=True)
	collection_image = models.ImageField(upload_to='images/', null=True, blank=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('collection_detail', args=[str(self.id)])


class CollectionType(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name


class CollectionItem(models.Model):
	uniqueId = models.CharField(max_length=100, help_text='Enter a unique name for this item')
	favorite = models.BooleanField()
	name = models.CharField(max_length=200, help_text='Enter a name for this item')
	quantity = models.IntegerField()
	rank = models.IntegerField()
	value = models.DecimalField(decimal_places=2, max_digits=100)
	notes = models.TextField()
	collectedDate = models.DateField()
	collection = models.ForeignKey('Collection', on_delete=models.RESTRICT, null=True)
	collectionItem_image = models.ImageField(upload_to='images/', null=True, blank=True)

	class Meta:
		ordering = ['rank']

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('collectionItem_detail', args=[str(self.id)])


class SiteUser(AbstractUser):
	private = models.BooleanField(null=True)
	description = models.TextField(null=True)
	user_image = models.ImageField(upload_to='images/', null=True, blank=True)

	def get_absolute_url(self):
		return reverse('profile', args=[str(self.id)])


class UserComment(models.Model):
	comment = models.TextField(max_length=200)
	siteUser = models.ForeignKey('SiteUser', on_delete=models.RESTRICT, null=True)
	collection = models.ForeignKey('Collection', on_delete=models.RESTRICT, null=True)

CollectAll/forms.py
from django.forms import ModelForm
from django import forms
from .models import Collection


class CollectionCreate(ModelForm):
    class Meta:
        model = Collection
        fields = ["name", "private", "favorite", "notes", "collectionType", "siteUser",'collection_image']
        widgets = {'siteUser': forms.HiddenInput()}

CollectAll/views.py
from .models import Collection, CollectionType, SiteUser, CollectionItem, UserComment
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from .forms import CollectionCreate
from django.http import HttpResponseRedirect
from django.urls import reverse


def search_collections(request):
    if request.method == "POST":
        searched = request.POST.get('searched')
        collections = Collection.objects.filter(name__icontains=searched)
        return render(request,'CollectAll/search_collections.html',{'searched': searched, "collections":collections})
    else:
        return render(request,'CollectAll/search_collections.html')


def index(request):
    return render(request, 'CollectAll/index.html')


class CollectionListView(generic.ListView):
    model = Collection

    def get_queryset(self):
        return Collection.objects.filter(private=False).filter(parent=None)


class CollectionDetailView(generic.DetailView):
    model = Collection


class PersonalCollectionListView(LoginRequiredMixin, generic.ListView):
    model = Collection
    template_name = 'CollectAll/personal_list.html'

    def get_queryset(self):
        return Collection.objects.filter(siteUser=self.request.user).filter(parent=None)


class ProfileView(generic.DetailView):
    model = SiteUser

    def user_profile(self):
        return self.request.user == SiteUser

def create_collection(request):
    if request.method == 'POST':
        form = CollectionCreate(request.POST)
        if form.is_valid():
            form.save()
            return redirect('personal_list')
    else:
        form = CollectionCreate(initial={"siteUser": request.user})
    return render(request, "CollectAll/collection_form.html", {"form": form})

class ProfileCreate(CreateView):
    model = SiteUser
    fields = ['first_name', 'last_name', 'SiteUser_image']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return self.request.user == SiteUser

class ProfileUpdate(UpdateView):
    model = SiteUser
    fields = ['first_name', 'last_name', 'SiteUser_image']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()
        return self.request.user == SiteUser


class CollectionUpdate(LoginRequiredMixin, UpdateView):
    model = Collection
    fields = ['name', 'private', 'favorite', 'notes', 'collectionType','collection_image']


def collection_delete(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    try:
        collection.delete()
        messages.success(request, (collection.name + " has been deleted"))
    except:
        messages.success(request, (collection.name + " cannot be deleted"))
    return redirect('personal_list')

CollectAll/templates/CollectAll/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CollectAll{% endblock %}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">CollectAll</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-
            label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'collection_list' %}">View Collections</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'personal_list' %}">My Collections</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'search_collections' %}">

            {% csrf_token %}

            <input class="form-control mr-sm-2" type="search" placeholder="Search Collections" aria-label="Search" name="searched">
            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li><a class="nav-link" href="{{ user.get_absolute_url }}">Profile</a> </li>
                <li><a class="nav-link" href="{% url 'logout' %}"><span
                    class="glyphicon glyphicon-log-in"></span>Logout</a>
                </li>
            {% else %}
                <li><a class="nav-link" href="{% url 'login' %}"><span
                    class="glyphicon glyphicon-log-in"></span>Login</a>
                </li>
                <li><a class="nav-link" href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span>Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    <br/>
    {% block content %}
    {% endblock %}
</div>
<!--<div class="container">
  <footer id="footer" class="site-footer fixed-bottom d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <span class="mb-3 mb-md-0 text-muted">© 2023 CollectAll</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3 px-2"><a class="text-muted" href="#">About</a></li>
      <li class="ms-3 px-2"><a class="text-muted" href="#">Contact Us</a></li>
    </ul>
  </footer>
</div>-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

CollectAll/templates/CollectAll/collection_deletion.html
{% extends "CollectAll/base.html" %}
{% block content %}
{% if user.is_authenticated and user == collection.user %}
<h1>Delete Collection {{ collection.first_name }}</h1>
<form method="Post">
{% csrf_token %}
<input type="submit" class="btn btn-danger"
value="Delete">
<a href="{% url 'index' pk=collection.id %}
">Cancel</a>
</form>
{% else %}
    You are not authorized to delete this collection
<a href="{% url 'index' %}">Home</a>
{% endif %}
{% endblock %}

CollectAll/templates/CollectAll/collection_detail.html
{% extends "CollectAll/base.html" %}
{% block content %}
    {% if collection.private == False or collection.private == True and collection.siteUser == user %}
<h1>Name: {{ collection.name }}</h1>

    <div>
    {% if collection.collection_image %}
        <img src="{{ collection.collection_image.url }}">
    {% endif %}
    </div>

<p><strong>Owner:</strong> <a href="">{{ collection.siteUser.username }}</a></p>
<div style="margin-left:20px;margin-top:20px">
<h4>Items</h4>
{% for subCollection in collection.collection_set.all %}
    <hr>
    <h5>{{ subCollection.name }}</h5>
{% endfor %}
{% for collectionItem in collection.collectionitem_set.all %}
<hr>
<h5>{{ collectionItem.name }}</h5>
    <p><strong>Quantity:</strong>{{ collectionItem.quantity }}</p>
    <p><strong>Value:</strong>{{ collectionItem.value }}</p>
    <p><strong>Collected:</strong>{{ collectionItem.collectedDate }}</p>
    <p><string>Notes:</string>{{ collectionItem.notes }}</p>
{% endfor %}
<p><string>Notes: </string>{{ collection.notes }}</p>
</div>
    {% else %}
    You are not authorized to view this collection
    {% endif %}
{% endblock %}

CollectAll/templates/CollectAll/collection_form.html
{% extends "CollectAll/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if collection and collection.siteUser == user or collection == None and user.is_authenticated %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You are not authorized to alter this collection.
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}

CollectAll/templates/CollectAll/collection_list.html
{% extends "CollectAll/base.html" %}
{% block content %}
<h1>Collection List</h1>
{% if collection_list %}
<ul>
{% for collection in collection_list %}
<li>
<a href="{{ collection.get_absolute_url }}">{{ collection.name }}</a>
    {% if collection.siteUser.private == False %}
    ({{ collection.siteUser.username }})
    {% endif %}
</li>
{% endfor %}
</ul>
{% else %}
<p>There are no existing collections.</p>
{% endif %}
{% endblock %}

CollectAll/templates/CollectAll/index.html
{% extends 'CollectAll/base.html' %}
{% block content %}
    <div class="container">
    <div class="row">
        <div class="col">
            <h2 class="py-5">
    CollectAll is a site where you get to show off your collectibles
    and connect with others who share similar interests.
                <p></p><p>Sign up to create your own collection board!</p>
            </h2>

        </div>
        <div class="col">
            TEST
        </div>
    </div>
    </div>

{% endblock %}

CollectAll/templates/CollectAll/personal_list.html
{% extends "CollectAll/base.html" %}
{% block content %}
<h1>Personal Collection List</h1>
    {% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show"
role="alert">
{{ message }}
<button type="button" class="btn-close" data-bs-
dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% if collection_list %}
<ul>
{% for collection in collection_list %}
        <li>
            <a href="{{ collection.get_absolute_url }}">{{ collection.name }}</a>
        {% if collection.collection_set.all or collection.collectionitem_set.all %}
            Cannot Delete
        {% else %}
            <a href="{% url 'collection_delete' pk=collection.pk %}"
                onclick="return confirm('Are you sure you want to delete?')"
            class="btn btn-danger">Delete</a>
        {% endif %}
            <a href="{% url 'collection_update' pk=collection.pk %}" class="btn btn-primary">Edit Collection</a>
        </li>
{% endfor %}
</ul>
{% else %}
<p>There are no existing collections.</p>
{% endif %}
    <a class="" href="{% url 'collection_create' %}">Add Collection</a>
{% endblock %}

CollectAll/templates/CollectAll/search_collections.html
{% extends "CollectAll/base.html" %}
{% block content %}

    {% if searched %}
        <h1>You searched for {{ searched }}</h1>
        <br/>
        {% for collections in collections %}
            <a href="{% url 'collection_detail' pk=collections.pk %}"> {{ collections }}</a> <br/>
        {% endfor %}


    {% else %}
        <h1> Hey! You forgot to search for a collection.</h1>
    {% endif %}


{% endblock %}

CollectAll/templates/CollectAll/siteUser_detail.html
{% extends "CollectAll/base.html" %}

{% block content %}
<h1>{{ siteuser.first_name }} {{ siteuser.last_name }}</h1>

<div class = "pictures">
    <div>
    {% if siteuser.user_image %}
        <img class="profile_pict" src="{{ siteuser.user_image.url }}">
    {% endif %}
    </div>
</div>

<p><strong>About Me: </strong>{{ siteuser.description }}</p>
    <h4>My Collections</h4>
    <hr>
{% if siteuser.collection_set.all %}
<ul>
{% for collection in siteuser.collection_set.all %}
<li>
<a href="{{ collection.get_absolute_url }}">{{ collection.name }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<p>There are no existing collections.</p>
{% endif %}

    <a href="{% url 'index' %}">Back to CollectAll Home</a>

{% endblock %}

CollectAll/templates/CollectAll/user_form.html
{% extends "CollectAll/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.catalog.create_user or perms.catalog.edit_user %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'index' %}">Home</a>
    {% endif %}
{% endblock %}